# Minimal values for local k3d development
# This simplifies all resource names to start with "obs"
fullnameOverride: "obs"

prometheus:
  prometheusSpec:
    # Reduce retention to save local disk/memory
    retention: 1d
    storageSpec:
      emptyDir:
        medium: Memory # Faster for local, lost on restart
    # Allow Prometheus to discover ServiceMonitors in any namespace
    serviceMonitorSelectorNilUsesHelmValues: false
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - prometheus.localhost
    path: /
    service.port: 9090

grafana:
  adminPassword: admin
  additionalDataSources:
    - name: Prometheus
      type: prometheus
      # The internal Kubernetes DNS URL:
      # http://[service-name].[namespace].svc.cluster.local:[port]
      # 'obs-prometheus' is the name generated when fullnameOverride is "obs"
      url: http://obs-prometheus.monitoring.svc.cluster.local:9090
      isDefault: true
  ingress:
      enabled: true
      ingressClassName: traefik
      hosts:
        - grafana.localhost
      path: /

# Disable components not strictly needed for model monitoring
alertmanager:
  enabled: false
prometheus-node-exporter:
  enabled: false
kubeStateMetrics:
  enabled: true # Keep this; useful for HPA/Pod status